apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: m-username
                  name: mongo-sec
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: m-password
                  name: mongo-sec
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: database_url
                  name: mongo-config
---
apiVersion: v1
kind: Service
metadata:
  name: express-ser
spec:
  selector:
    app: express
#  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
#      nodePort: 30000