version: "3"
services:
  certbot:
    build:
      context: ./certbot/docker
      dockerfile: Dockerfile
    container_name: certbot
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - TIMEWEB_API_KEY=${TIMEWEB_API_KEY}
      - DOMAINS=${DOMAINS:-logotipiwe.ru,*.logotipiwe.ru}
      - EMAIL=${EMAIL:-admin@logotipiwe.ru}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
    volumes:
      - ./nginx/ssl/all.logotipiwe.ru:/nginx-ssl:rw
      - ./certbot/logs:/var/log/letsencrypt:rw
      - ./certbot/scripts:/scripts:ro
    command: "cp /scripts/startup.sh /usr/local/bin/startup.sh && chmod +x /usr/local/bin/startup.sh && /usr/local/bin/startup.sh"
networks:
  dc-net:
    external: true