version: "3"
services:
  ms:
    container_name: ms
    image: mysql:8
    restart: always
    volumes:
    - msVol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dc-net
networks:
  dc-net:
    external: true
volumes:
  msVol:

