version: "3"
services:
  it_one_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${IT_ONE_PASS}
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pg:
    container_name: pg
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgVol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - dc-net
    ports:
      - 5432:5432
networks:
  dc-net:
    external: true
volumes:
  pgVol: