version: "3"
services:
  pma:
    container_name: pma
    image: 'phpmyadmin:5-apache'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ms
      PMA_PORT: 3306
    ports:
      - 30132:80
    networks:
      - dc-net
networks:
  dc-net:
    external: true