kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
  labels:
    type: local
spec:
#  storageClassName: pv-demo
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain

  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent-volume"