name: Infra CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_vars
          token: ${{secrets.PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Copy SSL cert
        run: |
          mkdir /tmp/deploy
          cp dc-vars-data/ssl /tmp/deploy -r
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_infrastructure
          token: ${{secrets.PAT}}
      - name: Set SSL cert
        run: |
          cp /tmp/deploy/ssl/* nginx/ssl/
          cd nginx/ssl
          ls
          cat logotipiwe.ru.crt
          cd /kuber/infra/
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infra
          remote: /kuber/infra
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            export MYSQL_ROOT_PASSWORD=${{env.MYSQL_ROOT_PASSWORD}}
            export DOZZLE_PASSWORD=${{env.DOZZLE_PASSWORD}}
            export DB_PASS=${{env.DB_PASS}}
            export PGADMIN_USER=${{env.PGADMIN_USER}}
            export PGADMIN_PASSWORD=${{env.PGADMIN_PASSWORD}}
            cd /kuber/infra/
            
            docker-compose $(ls *.yml|sed "s/^/-f /g"|xargs) down --remove-orphans
            docker-compose -f ingress.yml up -d
            docker-compose -f ms.yml up -d
            docker-compose -f pma.yml up -d
            docker-compose -f portainer.yml up -d
            docker-compose -f pg.yml up -d
            docker-compose -f pgadmin.yml up -d
