name: Certbot SSL Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[certbot]') || contains(github.event.head_commit.message, '[ssl]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_vars
          token: ${{secrets.PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_infrastructure
          token: ${{secrets.PAT}}
      - name: Upload certbot files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infra/certbot.yml
          remote: /kuber/infra/certbot.yml
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Upload certbot directory
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infra/certbot
          remote: /kuber/infra/certbot
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy certbot
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            export TIMEWEB_API_KEY=${{env.CERTBOT_TIMEWEB_API_KEY}}
            export TELEGRAM_BOT_TOKEN=${{env.CERTBOT_TELEGRAM_BOT_TOKEN}}
            export TELEGRAM_CHAT_ID=${{env.CERTBOT_TELEGRAM_CHAT_ID}}
            cd /kuber/infra/
            echo "Stopping existing certbot container..."
            docker-compose -f certbot.yml down
            
            echo "Building certbot image..."
            docker-compose -f certbot.yml build --no-cache
            
            echo "Starting certbot container..."
            docker-compose -f certbot.yml up -d