name: Cluster Up
on:
  push:
    branches: [ "deploy_all" ]
  workflow_dispatch:
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - id: step0
        run: echo "step 0!"
  job1:
    runs-on: ubuntu-latest
    uses: logotipiwe/dc_points_service/.github/workflows/test.yml@v1

