name: Cluster Up
on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step0
        run: echo "step 0!"
      - id: step1
        uses: logotipiwe/dc_points_service/.github/workflows/test.yml
