name: Cluster Up
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - id: step0
        run: echo "step 0!"
  job1:
    uses: logotipiwe/dc_points_service/.github/workflows/deploy.yml@dev
    secrets: inherit


