name: Deploy app some-app
on:
  workflow_call:
    inputs:
      repoName:
        type: string
        required: true
    secrets:
      pat:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vars
        uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_vars
          token: ${{secrets.pat}}

      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: Logotipiwe/${{inputs.repoName}}
          token: ${{secrets.pat}}

      - name: Build
        id: build_push
        run: |
          ls
          export IMAGE=${{ env.DOCKER_USER }}/points-service:$(date +%s)
          docker build . -t ${IMAGE}
          docker push ${IMAGE}
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"